Repository inkua/maqueta-ong, pull requests merged in 2023-04, with the labels that each got.

#2 Update README.md
  README.md
Labels: codeball:approved

#4 Update code-review.yml
  .github/workflows/code-review.yml
Labels: codeball:approved

#3 Update .gitignore
  .gitignore
Labels: codeball:needs-review

#13 Fix/production deployment
  src/App.test.tsx
  src/components/Header.jsx
Labels: codeball:needs-careful-review

#14 Update README.md
  README.md
Labels: codeball:approved

#15 migration and configuration to next.js, plus routing
  .editorconfig
  .gitignore
  index.d.ts
  next-env.d.ts
  next.config.js
  package-lock.json
  package.json
  public/favicon.ico
  public/images/prueba.txt
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.test.tsx
  src/App.tsx
  src/components/Header/Header.jsx
  src/components/Layout/Layout.tsx
  src/contexts/about.txt
  src/hooks/about.txt
  src/index.css
  src/index.tsx
  src/logo.svg
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/about-us/index.tsx
  src/pages/donate/index.tsx
  src/pages/get-help/index.tsx
  src/pages/index.tsx
  src/pages/news/index.tsx
  src/pages/volunteer-form/index.tsx
  src/pages/volunteer/index.tsx
  src/react-app-env.d.ts
  src/reportWebVitals.ts
  src/setupTests.ts
  src/styles/about.txt
  tsconfig.json
Labels: codeball:needs-careful-review

#19 feat:footer ready
  src/assets/facebook-logo.png
  src/assets/instagram-logo.png
  src/assets/ong-logo.png
  src/assets/whatsApp-logo.png
  src/components/Footer/Footer.tsx
  src/components/Footer/footer.module.css
  src/components/Header/Header.tsx
  src/components/Layout/Layout.tsx
  src/data/ong.ts
  src/pages/_app.tsx
  src/styles/globals.css
Labels: codeball:needs-careful-review
